<ol>
  <li>
    <button>
      <span>Maandag</span>
      <span>17</span>
    </button>
  </li>
  <li>
    <button>
      <span>Dinsdag</span>
      <span>18</span>
    </button>
  </li>
  <li>
    <button>
      <span>Woensdag</span>
      <span>19</span>
    </button>
  </li>
  <li>
    <button>
      <span>Donderdag</span>
      <span>20</span>
    </button>
  </li>
  <li>
    <button>
      <span>Vrijdag</span>
      <span>21</span>
    </button>
  </li>
  <li>
    <button>
      <span>Zaterdag</span>
      <span>22</span>
    </button>
  </li>
  <li>
    <button>
      <span>Zondag</span>
      <span>23</span>
    </button>
  </li>
</ol>
